USE ROLE ACCOUNTADMIN;

-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE FRED_ROLE;
GRANT ROLE FRED_ROLE TO ROLE SYSADMIN;
GRANT ROLE FRED_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE FRED_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE FRED_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE FRED_ROLE;

-- Databases
CREATE OR REPLACE DATABASE FRED_DB;
GRANT OWNERSHIP ON DATABASE FRED_DB TO ROLE FRED_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE FRED_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE FRED_WH TO ROLE FRED_ROLE;


-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
USE ROLE FRED_ROLE;
USE WAREHOUSE FRED_WH;
USE DATABASE FRED_DB;

-- Schemas
CREATE OR REPLACE SCHEMA EXTERNAL;
CREATE OR REPLACE SCHEMA RAW_DAILY;
CREATE OR REPLACE SCHEMA RAW_MONTHLY;
CREATE OR REPLACE SCHEMA RAW_WEEKLY;
CREATE OR REPLACE SCHEMA HARMONIZED;
CREATE OR REPLACE SCHEMA ANALYTICS;

--stage creation
CREATE OR REPLACE STAGE FRED_RAW_STAGE;

-- Create the storage integration
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE STORAGE INTEGRATION fred_s3_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::699475925561:role/snowflake_s3_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://fredcurrencyexhange/');
GRANT USAGE ON INTEGRATION fred_s3_integration TO ROLE FRED_ROLE;

-- Create the file format
USE ROLE FRED_ROLE;
USE WAREHOUSE FRED_WH;
USE DATABASE FRED_DB;
USE SCHEMA EXTERNAL;
CREATE OR REPLACE FILE FORMAT CSV_FORMAT 
TYPE = 'CSV' 
FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
PARSE_HEADER = TRUE;


-- Create the UDF
CREATE OR REPLACE FUNCTION HARMONIZED.USD_CONVERSION_UDF(EXCHANGE_RATE NUMBER(35,4))
RETURNS NUMBER(35,4)
LANGUAGE SQL
AS
$$
    CASE 
        WHEN EXCHANGE_RATE = 0 THEN 0
        ELSE 1 / EXCHANGE_RATE
    END
$$;
